[package]
name = "crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest.workspace = true
tracing.workspace = true
anyhow.workspace = true
dashmap.workspace = true
scraper.workspace = true
url.workspace = true
tokio.workspace = true
csv.workspace = true
serde.workspace = true
